# Site
name: "Batos Jugando"
title: "Batos Jugando"
description: "Somos un grupo de fanáticos de los videojuegos, transmitimos nuestras partidas por streaming, publicamos un podcast semanal llamado El Hongo Verde, componemos música, creamos videojuegos, a veces también publicamos arte digital, etc. Bien inquietos somos los Batos Jugando."
meta_description: "Somos un grupo de fanáticos de los videojuegos, transmitimos nuestras partidas por streaming, publicamos un podcast semanal llamado El Hongo Verde, componemos música, creamos videojuegos, a veces también publicamos arte digital, etc. Bien inquietos somos los Batos Jugando."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
paginate: 6
baseurl: '/'
email: 'hola@gatomocho.com'
google_analytics: 'UA-165370115-1'
disqus: 'batosjugando'

# Links
menu:
  - title: Inicio
    url: /
  - title: Podcast
    url: /podcast
  - title: Quedate en Casa
    url: /en-casa
  - title: Discord
    url: http://discord.batosjugando.com
    external: true
  - title: Patreon
    url: https://www.patreon.com/elhongoverde
    external: true

# Sidebar > Cyber-Amigos
cyber-amigos:
  - title: GatoMocho Game Studio
    url: https://gatomocho.com
  - title: Rancheros Tiernos
    url: https://anchor.fm/rancherostiernos/
  - title: Maleducados
    url: https://www.instagram.com/maleducados/
  - title: Gato Gordo
    url: https://www.instagram.com/gatogordocc/

# Sidebar > Recomendado
recomendado:
  - title: "Valorya: The Blacksmith"
    image: https://i.imgur.com/KWZ1WyJ.png
    url: https://gatomocho.com/game/valorya-blacksmith

# Footer > Nuestras Redes
redes:
  - title: Discord
    icon: "fa fa-comment"
    url: http://discord.batosjugando.com
  - title: Twitter
    icon: "fa fa-twitter"
    url: https://www.twitter.com/batosjugando
  - title: Twitch
    icon: "fa fa-twitch"
    url: https://www.twitch.tv/batosjugando
  - title: Instagram
    icon: "fa fa-instagram"
    url: https://www.instagram.com/batosjugando
  - title: Facebook
    icon: "fa fa-facebook"
    url: https://www.facebook.com/batosquejuegan
  - title: Youtube
    icon: "fa fa-youtube"
    url: https://www.youtube.com/channel/UCU40Vk0baBrI998m5aGyZ2w

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

collections:
  pages:
    output: true
    permalink: /page/:name
    
# Other
markdown: kramdown
highlighter: rouge
